# Streamlit secrets configuration
# Add your API keys and sensitive information here
# This file should be added to .gitignore for security

# Example API keys (replace with actual keys)
[api_keys]
# openai_api_key = "your-openai-api-key-here"
# binance_api_key = "your-binance-api-key"
# coinbase_api_key = "your-coinbase-api-key"

# Database configuration (if needed)
[database]
# host = "localhost"
# port = 5432
# database = "crypto_analyzer"
# username = "your-username"
# password = "your-password"